### ISSUE TITLE
Todo: Main 

### ISSUE THREAD

**Issue by Akilan1999** [Akilan1999/p2p-rendering-computation#84]
- [x] Fix Mac detect node configuration. 
- [x] Play around with head scale and get a test configuration setup. 
- [ ] Write basic plan to setup head scale.

**Comment by Akilan1999** [comment]
Plan diverted to use FRP.
